on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Upload to Release(zip)
      uses: svenstaro/upload-release-action@v2
      with: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/distributions/omegat-oxford-dictionaries-${{ steps.get_version.outputs.VERSION }}.zip
        tag: ${{ github.ref }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
    - name: Upload to Release(jar)
      uses: svenstaro/upload-release-action@v2
      with: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/omegat-oxford-dictionaries-${{ steps.get_version.outputs.VERSION }}.jar
        tag: ${{ github.ref }}
